name: Vulnerability Scan

on:
  workflow_dispatch:
    inputs:
      rapidscan:
        description: "Arguments passed to run Scan"
        required: false
      target:
        description: "Target for the scan"
        required: false

env:
  BUILD_ARGS: ${{ secrets.RAPIDSCAN }}  # Using secrets to avoid exposing sensitive data
  WORKING_DIRECTORY: ${{ github.event.inputs.target }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true # Temporary; ensure to remove this in production once GitHub Actions support fully secure commands

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure code is checked out if needed

      - name: Set target environment variable
        run: echo "TARGET=${{ github.event.inputs.target }}" >> $GITHUB_ENV

      - name: Pull and run Docker container
        run: |
          docker build -t rapidscan .
          docker run -t rapidscan python3 /usr/local/bin/rapidscan.py ${{ github.event.inputs.rapidscan }} ${{ env.TARGET }}

      - name: Vulnerability Scan
        uses: ghcr.io/threatcode/rapidscan@master
        with:
          args: "${{ github.event.inputs.rapidscan }} ${{ env.TARGET }}"
